language: node_js
install:
  - npm update -g npm
  - npm install -g typescript
  - npm install
script: npm test
node_js:
  - '6'
  - '7'
  - '8'
cache:
  directories:
  - $HOME/.npm

jobs:
  include:
    - stage: npm release
      node_js: '8'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: engineering@foundry.ai
        api_key:
          secure: guZabVR5wR+izJz521BrGeaYlkWabMXwdz65oU5VRkconX12p/s+MjDrdw6uPb81yKyQ+Ykfkpi1pE2/dbAc8Ofq+bEFBiv8teBssRFT7u90VIFifJI6QCO783e1Ybt4V+Y9ple61UdUgHCWAWqvkwcJ+wr7tJKb30ZjT4c/6nSvZuTFsUMY/Hb5yZV5snpQxjMZEvgTiO0hHoPFEtz5r94Corxz9WsjDOOQ4dqGot/pXolnEa7fSMwfjiHlk/gLRYVSInAVRqg6gen5LSgveVL0N36jZHb60NNDGP7v8Z9nIIA72FiPGabU/MsRqcdeQFyUxieMg5rDtKn949y+LfHKtQULjtSygQcX4RFAElz8Kns+piQj+JQwJ2M1IJL1OLvjZZFWuD0dBjoa3vqpqa6K13WX1bNa3tZto77378SKVlvL+7d+94X7qSA/+gnjuWYfwZJT/PDGAfDNGLgHlTtJpcGI8CdPAWdeYCNjSj8inpqNSvl0ClQjdXUmwan9FlTz3NIyqxo9tU0sh+6hT6m7Yyze8m0tbC+cjs65kMAWNn9uVS+V0CopfxulMOZI4A5rif8z5hwimSUbwNE6Ra7pz3Ie4Aqs+33ZHOfcFbK2cuWQGCTWmwXdjtu+5EdqcVtfnYF/LKhFMFwn+NAZn/rK9PN8I0bmUcAwUIRhRcY=
        on:
          tags: true
