export { ArticleResource } from './Article';
export { ArticleHighlightResource } from './ArticleHighlight';
export { CompanyResource } from './Company';
export { CompanyKeyTermResource } from './CompanyKeyTerm';
export { DomainResource } from './Domain';
export { KeyTermResource } from './KeyTerm';
export { RelevantArticleResource } from './RelevantArticle';
export { TextCorpusResource } from './TextCorpus';
export { UserResource } from './User';
